
name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 180
    env:
      MPIEXEC_FLAGS: "--allow-run-as-root --oversubscribe"

    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Install Ubuntu packages
      run: |
        sudo apt-get update
        sudo apt-get install python3 mpi-default-bin mpi-default-dev libmetis-dev libparmetis-dev libsuitesparse-dev

    - name: Install Python dependencies
      run: make prereq && make prereq-extra

    - name: Install
      run: make install

    - name: Run tests
      run: make tests

    - name: Archive test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-report
        path: index.html
        
    - name: HTML Preview
      id: html_preview
      uses: pavi2410/html-preview-action@v2
      if: always()
      with:
        html_file: 'index.html'
        
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      if: always()
      with: 
        message: |
          ${{steps.html_preview.outputs.url}}
